name: memorify
description: app for training your memory
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.4.0
  bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  talker: ^3.0.0+1
  talker_bloc_logger: ^2.0.0
  talker_flutter: ^3.1.1

dev_dependencies:
  auto_route_generator: ^7.1.1
  bloc_test: ^9.1.3
#  flutter_test:
#    sdk: flutter
  build_runner:
  hive_generator: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.24.3
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/files/words-ru.txt

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf

